### ISSUE TITLE
Using nre from a macro

### ISSUE THREAD

**Issue by bluenote10** [flaviut/nre#17]
My plan was to use nre from within a macro. However, a simple test like this

```
import nre
import macros

macro test(): stmt =
  let match = "hello".match(re"h")
  result = newStmtList()

test()
```

results in `/nre.nim(281, 24) Error: cannot 'importc' variable at compile time` (call to `pcre.compile`). I don't know if that is something that can be easily solved, or whether it is a general problem with macros. But since macros often deal with parsing, it would definitely be nice to have regular expressions available.

Note: Looks like using nre from templates is not a problem.

**Comment by flaviut** [comment]
This is impossible to fix from nre's side.

nre calls out to PCRE in order to actually perform the matching, which is
written in C.

Code in macros is executed by a virtual machine in the Nim compiler, but
that VM does not support any sort of FFI.

Templates work fine because they don't run the code they contain at compile
time. Doing `parseStmt"re""foo"""` in a macro will do the same thing and
should work fine.

**Comment by bluenote10** [comment]
Thanks for the clarification -- I just didn't know about ffi and macros.
