### ISSUE TITLE
nre.escapeRe is not gcsafe

### ISSUE THREAD

**Issue by mildred** [flaviut/nre#25]
To use nre in a gcsafe environment, it would be great to have `escapeRe` to be gcsafe.

**Comment by mildred** [comment]
https://github.com/flaviut/nre/blob/52f8117d3b8f2bfc6f94616b2b676c434b59c4f7/src/nre.nim#L765-L769

The problem is that `SpecialCharMatcher` is a global mutable variable and that `escapeRe` may be called from a thread that is not the main thread. In this case the `SpecialCharMatcher` variable may enter the thread and may be subject to the thread garbage collector while it is used in another thread.

Ideally, it should be made `const` and I believe this could solve the issue but the compiler refuses to mark regular expressions as `const` for some reason (`cannot 'importc' variable at compile time; compile`).

Another solution could be to use a thread variable for this, and initialize it on demand. Not that nice...

**Comment by flaviut** [comment]
I'd recommend you file this issue in the Nim repo, since this repo
isn't used anymore (unless they've changed their mind and removed nre
from the stdlib).

"The compiler must be able to evaluate the expression in a constant
declaration at compile time"--so that's why const won't work here.

Perhaps `{.cast(gcsafe).}:` would work here? I'm not 100% sure what
gcsafe means, but regex patterns are definitely threadsafe: "The
compiled form of a regular expression is not altered during matching,
so the same compiled pattern can safely be used by several threads at
once".

And while it does contain some GC'd data, the global lifetime of the
pattern should mean that none of it ever gets deallocated. But it's
been a long time since I've worked with Nim, so I'm not sure.

**Comment by mildred** [comment]
Thanks, I moved the issue

**Comment by flaviut** [comment]
Fixed by https://github.com/nim-lang/Nim/pull/16109, thanks :)
