### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by axbender** [flaviut/nre#3]
How would I integrate this using Windows?
I see no option for building pcre here (nor a batch to test it)...

**Comment by flaviut** [comment]
It should Just Work. I've bundled a copy of PCRE [here](https://github.com/flaviut/nre/tree/master/src/private/pcre_src), and the Nim compiler with compile it for you because of [these lines](https://github.com/flaviut/nre/blob/master/src/private/pcre.nim#L14-L36).

If compiling a test module fails, try deleting `nimcache` and try again. If it still fails, post the output of the command here.

**Comment by axbender** [comment]
I keep getting "nre.nim(8, 7) Error: cannot open 'optional_t'" when compiling with "nim c -d:release nre.nim" from "src"...

Btw. Araq mentioned he would consider adopting "nre" if you would be willing to maintain it. Given the shortcomings of "re", I'd really appreciate such a committment of your's.

**Comment by flaviut** [comment]
Did you install nre with nimble? I depend on another package, [optional_t](https://github.com/flaviut/nre/blob/master/nre.nimble#L11) for the option type. If that's not installed, it'll fail to compile.

I am committed to maintaining nre, but I'd prefer to go in the opposite direction, keeping stdlib lean and requiring that users install other packages separately.

**Comment by oprypin** [comment]
There is nothing to talk about here. _nre_ definitely works out of the box on Windows, you are just doing something wrong (why would you compile a library as an executable?).

If you really want to work around using _nimble_, you can copy the _src_ directories of the two libraries, renaming them to the respective names, to your project's directory.

In any case you should not _compile_ libraries.

**Comment by axbender** [comment]
@BlaXpirit: I'am pretty sure I'm doing sth. wrong. However, according to the manual
"nim c -d:useNimRtl pcre.nim" could have done the trick (obviously it doesn't).
@flaviut: Could you give me some directions as how I can correctly install the package and compile it?
I'm pretty new to Nim and haven't use nimble so far.

**Comment by flaviut** [comment]
@BlaXpirit 
@axbender is not attacking me personally, he's just looking for help. No need to get upset.

@axbender
After you install nimble and add it to your path, `nimble install nre` should do what you want. You can also get the source files out of the [optional_t](https://github.com/flaviut/optional_t) module and copy them in place manually.
Instead of `nim c -d:useNimRtl pcre.nim`, you should be using `nim c -d:useNimRtl nre.nim`. `pcre.nim` is an internal module, you shouldn't use it on it's own.

**Comment by axbender** [comment]
@flaviut: Sorry for reporting back so lately. Following your instructions I was able to install nre. Now I'm going to look at it. Thanks!
Addendum: Yesterday evening, when trying to install nre on another PC, nimble kept downloading optional_t 1.1.0. This morning (at least in Germany ;-), from another PC, it worked fine. Did you update the repository?

@BlaXpirit: Thanks for commenting on my question in the forum and providing me with a first solution! I will elaborate on it...

**Comment by flaviut** [comment]
@axbender Yep, I noticed that I had tagged 1.2.0 but forgotten to bump the version number in the nimble file, leading to nimble getting confused.
Fixed in flaviut/optional_t@9f33a000cfadb4ffe0a404798147dea90fed66c4
